// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlc8Gs6FduNnbyijzOPTXenRACaz_07JU',
    appId: '1:959949539242:web:d980b0bde43b051e6a8dd3',
    messagingSenderId: '959949539242',
    projectId: 'iot-app-ffa8e',
    authDomain: 'iot-app-ffa8e.firebaseapp.com',
    storageBucket: 'iot-app-ffa8e.firebasestorage.app',
    measurementId: 'G-2C2T0YJW5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV8aLATWWICERCvwSPY3xfGXtC2jEMo5Y',
    appId: '1:959949539242:android:65daf268ff416dd06a8dd3',
    messagingSenderId: '959949539242',
    projectId: 'iot-app-ffa8e',
    storageBucket: 'iot-app-ffa8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq6ok_r3OZmjJr1vDcUA9YuL1SaBB4P6c',
    appId: '1:959949539242:ios:286442c623b1af6b6a8dd3',
    messagingSenderId: '959949539242',
    projectId: 'iot-app-ffa8e',
    storageBucket: 'iot-app-ffa8e.firebasestorage.app',
    iosBundleId: 'com.example.homeAutomationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq6ok_r3OZmjJr1vDcUA9YuL1SaBB4P6c',
    appId: '1:959949539242:ios:286442c623b1af6b6a8dd3',
    messagingSenderId: '959949539242',
    projectId: 'iot-app-ffa8e',
    storageBucket: 'iot-app-ffa8e.firebasestorage.app',
    iosBundleId: 'com.example.homeAutomationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlc8Gs6FduNnbyijzOPTXenRACaz_07JU',
    appId: '1:959949539242:web:0508646fd0bbe5926a8dd3',
    messagingSenderId: '959949539242',
    projectId: 'iot-app-ffa8e',
    authDomain: 'iot-app-ffa8e.firebaseapp.com',
    storageBucket: 'iot-app-ffa8e.firebasestorage.app',
    measurementId: 'G-HZ2R1K7JPL',
  );
}
